// AUTO-GENERATED by scripts/regen-sms-contracts.ts. DO NOT EDIT BY HAND.
// Source: src/lib/sms/sms-contracts.source.ts
// To refresh: npx tsx scripts/regen-sms-contracts.ts
//
// Per-slug typed render-vars contract for renderSmsTemplate.
//
// CONTRACTS_BY_SLUG mirrors the DB shape exactly (same arrays as
// sms_templates.required_variables / optional_variables). RenderVarsBySlug
// is the type the engine signature is generic over — for each slug, an
// object type where required chips are required string properties and
// optional chips are `string | undefined` optional properties.
//
// Auto-inject override: chips with `autoInject: true` in the palette are
// always typed as OPTIONAL in every slug, even when the slug contract lists
// them as required. The engine fills them before the hard-skip pre-check, so
// callers never need to plumb the value through. Currently 3 chips:
//   business_name, business_phone, business_address

// ── Slug enum ──────────────────────────────────────────────────────────────

export const SMS_SLUGS = [
  "addon_approved",
  "addon_declined",
  "appointment_cancelled",
  "appointment_confirmed",
  "appointment_confirmed_postcall",
  "booking_confirmed",
  "booking_reminder",
  "booking_staff_notify",
  "detailer_job_assigned",
  "job_complete",
  "loyalty_milestone",
  "payment_receipt",
  "quote_accepted_multi",
  "quote_accepted_single",
  "quote_accepted_staff_notify",
  "quote_reminder",
  "quote_viewed_followup",
  "staff_notification",
] as const;

export type SmsSlug = (typeof SMS_SLUGS)[number];

// ── Raw contracts (DB mirror) ──────────────────────────────────────────────

export interface SmsContract {
  readonly required: readonly string[];
  readonly optional: readonly string[];
}

export const CONTRACTS_BY_SLUG: { readonly [S in SmsSlug]: SmsContract } = {
  addon_approved: { required: ["service_name"], optional: ["first_name", "last_name", "vehicle_description"] },
  addon_declined: { required: ["service_name"], optional: ["first_name", "last_name", "vehicle_description"] },
  appointment_cancelled: { required: ["business_name", "business_phone"], optional: ["first_name", "services", "appointment_date", "appointment_time", "last_name", "vehicle_description"] },
  appointment_confirmed: { required: ["service_name", "appointment_date", "appointment_time", "business_name", "business_phone"], optional: ["first_name", "service_total", "last_name", "vehicle_description"] },
  appointment_confirmed_postcall: { required: ["business_name", "business_phone"], optional: ["first_name", "last_name"] },
  booking_confirmed: { required: ["services", "appointment_date", "appointment_time", "service_total", "business_name", "business_phone"], optional: ["first_name", "last_name", "vehicle_description"] },
  booking_reminder: { required: ["service_name", "appointment_time", "business_name", "business_phone"], optional: ["first_name", "last_name", "vehicle_description"] },
  booking_staff_notify: { required: ["customer_name", "services", "appointment_date", "appointment_time", "deposit_info"], optional: ["customer_email", "customer_phone", "last_name", "vehicle_description"] },
  detailer_job_assigned: { required: ["job_summary", "appointment_date", "appointment_time", "service_total"], optional: ["mobile_service_address", "detailer_first_name", "customer_email", "customer_phone", "last_name"] },
  job_complete: { required: ["gallery_link", "business_name", "business_address", "business_phone", "hours_line"], optional: ["first_name", "vehicle_description", "last_name"] },
  loyalty_milestone: { required: ["loyalty_points_balance", "loyalty_cash_value", "booking_link", "business_name"], optional: ["first_name", "last_name"] },
  payment_receipt: { required: ["transaction_greeting", "receipt_link", "business_name"], optional: ["first_name", "last_name"] },
  quote_accepted_multi: { required: [], optional: ["first_name", "last_name"] },
  quote_accepted_single: { required: ["item_name"], optional: ["first_name", "last_name", "vehicle_description"] },
  quote_accepted_staff_notify: { required: ["customer_name", "quote_number", "services", "service_total"], optional: ["customer_phone", "customer_email", "last_name", "vehicle_description"] },
  quote_reminder: { required: ["first_name", "short_url"], optional: ["last_name", "vehicle_description"] },
  quote_viewed_followup: { required: ["first_name", "short_url"], optional: ["last_name", "vehicle_description"] },
  staff_notification: { required: ["reason_label", "customer_name", "details", "customer_phone"], optional: ["customer_email", "last_name", "vehicle_description"] },
};

// ── Per-slug render-vars types ─────────────────────────────────────────────

export interface RenderVarsBySlug {
  addon_approved: {
    service_name: string;
    first_name?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  addon_declined: {
    service_name: string;
    first_name?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  appointment_cancelled: {
    business_name?: string | undefined;
    business_phone?: string | undefined;
    first_name?: string | undefined;
    services?: string | undefined;
    appointment_date?: string | undefined;
    appointment_time?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_address?: string | undefined;
  };
  appointment_confirmed: {
    service_name: string;
    appointment_date: string;
    appointment_time: string;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    first_name?: string | undefined;
    service_total?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_address?: string | undefined;
  };
  appointment_confirmed_postcall: {
    business_name?: string | undefined;
    business_phone?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    business_address?: string | undefined;
  };
  booking_confirmed: {
    services: string;
    appointment_date: string;
    appointment_time: string;
    service_total: string;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_address?: string | undefined;
  };
  booking_reminder: {
    service_name: string;
    appointment_time: string;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_address?: string | undefined;
  };
  booking_staff_notify: {
    customer_name: string;
    services: string;
    appointment_date: string;
    appointment_time: string;
    deposit_info: string;
    customer_email?: string | undefined;
    customer_phone?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  detailer_job_assigned: {
    job_summary: string;
    appointment_date: string;
    appointment_time: string;
    service_total: string;
    mobile_service_address?: string | undefined;
    detailer_first_name?: string | undefined;
    customer_email?: string | undefined;
    customer_phone?: string | undefined;
    last_name?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  job_complete: {
    gallery_link: string;
    hours_line: string;
    business_name?: string | undefined;
    business_address?: string | undefined;
    business_phone?: string | undefined;
    first_name?: string | undefined;
    vehicle_description?: string | undefined;
    last_name?: string | undefined;
  };
  loyalty_milestone: {
    loyalty_points_balance: string;
    loyalty_cash_value: string;
    booking_link: string;
    business_name?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  payment_receipt: {
    transaction_greeting: string;
    receipt_link: string;
    business_name?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  quote_accepted_multi: {
    first_name?: string | undefined;
    last_name?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  quote_accepted_single: {
    item_name: string;
    first_name?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  quote_accepted_staff_notify: {
    customer_name: string;
    quote_number: string;
    services: string;
    service_total: string;
    customer_phone?: string | undefined;
    customer_email?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  quote_reminder: {
    first_name: string;
    short_url: string;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  quote_viewed_followup: {
    first_name: string;
    short_url: string;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
  staff_notification: {
    reason_label: string;
    customer_name: string;
    details: string;
    customer_phone: string;
    customer_email?: string | undefined;
    last_name?: string | undefined;
    vehicle_description?: string | undefined;
    business_name?: string | undefined;
    business_phone?: string | undefined;
    business_address?: string | undefined;
  };
}

/** Ergonomic per-slug render-vars helper. */
export type SmsRenderVars<S extends SmsSlug> = RenderVarsBySlug[S];
