// AUTO-GENERATED by scripts/regen-sms-contracts.ts. DO NOT EDIT BY HAND.
// Source: src/lib/sms/sms-contracts.source.ts
// To refresh: npx tsx scripts/regen-sms-contracts.ts
//
// Universal SMS chip palette. Single flat record of every chip the SMS engine
// can recognize. The Zod contract validator in src/lib/sms/contract.ts rejects
// any DB contract referencing a chip not listed here.
//
// Conventions:
//   - `format` is a display hint for the admin UI preview. The engine itself
//     does no formatting.
//   - `composite: true` flags chips built by helpers in src/lib/sms/composites.ts.
//   - `autoInject: true` flags chips the engine fills from getBusinessInfo()
//     before the hard-skip pre-check.

export interface ChipMetadata {
  /** Chip key as it appears in template body: {key} */
  key: string;
  /** Human-readable description for admin UI tooltips */
  description: string;
  /** Sample value for admin UI preview rendering */
  sample: string;
  /** Display format hint */
  format?: 'currency' | 'date' | 'time' | 'phone' | 'url' | 'plain';
  /** Caller-built composite (built by helpers in composites.ts) */
  composite?: boolean;
  /** Engine auto-injects from getBusinessInfo() (callers may omit) */
  autoInject?: boolean;
}

export const SMS_PALETTE: Record<string, ChipMetadata> = {
  first_name: { key: "first_name", description: "Customer first name", sample: "John", format: "plain" },
  last_name: { key: "last_name", description: "Customer last name", sample: "Smith", format: "plain" },
  customer_name: { key: "customer_name", description: "Customer full name", sample: "John Smith", format: "plain" },
  customer_phone: { key: "customer_phone", description: "Customer phone (formatted)", sample: "(310) 555-1234", format: "phone" },
  customer_email: { key: "customer_email", description: "Customer email address", sample: "john@example.com", format: "plain" },
  vehicle_description: { key: "vehicle_description", description: "Cleaned vehicle description (year/make/model)", sample: "2024 Tesla Model 3", format: "plain" },
  vehicle_year: { key: "vehicle_year", description: "Vehicle year", sample: "2024", format: "plain" },
  vehicle_make: { key: "vehicle_make", description: "Vehicle make", sample: "Tesla", format: "plain" },
  vehicle_model: { key: "vehicle_model", description: "Vehicle model", sample: "Model 3", format: "plain" },
  vehicle_color: { key: "vehicle_color", description: "Vehicle color", sample: "Black", format: "plain" },
  size_class: { key: "size_class", description: "Vehicle size class", sample: "sedan", format: "plain" },
  license_plate: { key: "license_plate", description: "Vehicle license plate", sample: "ABC1234", format: "plain" },
  business_name: { key: "business_name", description: "Business name", sample: "[From Settings]", format: "plain", autoInject: true },
  business_phone: { key: "business_phone", description: "Business phone number", sample: "[From Settings]", format: "phone", autoInject: true },
  business_address: { key: "business_address", description: "Business address", sample: "[From Settings]", format: "plain", autoInject: true },
  business_email: { key: "business_email", description: "Business email", sample: "[From Settings]", format: "plain" },
  business_website: { key: "business_website", description: "Business website URL", sample: "[From Settings]", format: "url" },
  business_hours: { key: "business_hours", description: "Business hours (raw)", sample: "Mon-Fri 9-6", format: "plain" },
  receipt_number: { key: "receipt_number", description: "Transaction receipt number", sample: "R-001234", format: "plain" },
  service_total: { key: "service_total", description: "Service / appointment total amount", sample: "$299.00", format: "currency" },
  total_amount: { key: "total_amount", description: "Total amount (raw, may include tip+tax)", sample: "$329.45", format: "currency" },
  tax_total: { key: "tax_total", description: "Tax portion of total", sample: "$26.91", format: "currency" },
  subtotal: { key: "subtotal", description: "Subtotal before tax/tip", sample: "$299.00", format: "currency" },
  tip_amount: { key: "tip_amount", description: "Tip portion of total", sample: "$45.00", format: "currency" },
  payment_method: { key: "payment_method", description: "Payment method", sample: "Card", format: "plain" },
  discount_amount: { key: "discount_amount", description: "Discount applied to transaction", sample: "$25.00", format: "currency" },
  loyalty_points_earned: { key: "loyalty_points_earned", description: "Loyalty points earned this transaction", sample: "299", format: "plain" },
  loyalty_points_balance: { key: "loyalty_points_balance", description: "Customer loyalty points balance", sample: "500", format: "plain" },
  loyalty_cash_value: { key: "loyalty_cash_value", description: "Cash equivalent of loyalty points", sample: "$25.00", format: "currency" },
  appointment_date: { key: "appointment_date", description: "Appointment date", sample: "Monday, March 28, 2026", format: "date" },
  appointment_time: { key: "appointment_time", description: "Appointment time", sample: "10:30 AM", format: "time" },
  appointment_id: { key: "appointment_id", description: "Appointment UUID", sample: "a1b2c3d4-…", format: "plain" },
  estimated_duration: { key: "estimated_duration", description: "Estimated appointment duration", sample: "90 minutes", format: "plain" },
  scheduled_end_time: { key: "scheduled_end_time", description: "Scheduled appointment end time", sample: "12:00 PM", format: "time" },
  channel: { key: "channel", description: "Booking channel (online, voice, walk-in)", sample: "online", format: "plain" },
  mobile_service_address: { key: "mobile_service_address", description: "Mobile service address (where the detailer goes)", sample: "123 Main St, Torrance, CA", format: "plain" },
  job_id: { key: "job_id", description: "Job UUID", sample: "j1b2c3d4-…", format: "plain" },
  job_status: { key: "job_status", description: "Job status", sample: "in_progress", format: "plain" },
  detailer_first_name: { key: "detailer_first_name", description: "Assigned detailer's first name", sample: "Mike", format: "plain" },
  detailer_name: { key: "detailer_name", description: "Assigned detailer's full name", sample: "Mike Johnson", format: "plain" },
  gallery_link: { key: "gallery_link", description: "Photo gallery link for this job", sample: "https://sdas.co/g5678", format: "url" },
  job_duration: { key: "job_duration", description: "Total job duration (from final timer)", sample: "2h 15m", format: "plain" },
  quote_number: { key: "quote_number", description: "Quote number", sample: "Q-001234", format: "plain" },
  quote_url: { key: "quote_url", description: "Customer-facing quote URL", sample: "https://sdas.co/q1234", format: "url" },
  valid_until: { key: "valid_until", description: "Quote expiration date", sample: "April 30, 2026", format: "date" },
  validity_days: { key: "validity_days", description: "Number of days the quote is valid", sample: "30", format: "plain" },
  item_name: { key: "item_name", description: "Single quote item name", sample: "Ceramic Coating", format: "plain" },
  services: { key: "services", description: "Comma-joined list of service names", sample: "Ceramic Coating, Interior Detail", format: "plain" },
  service_name: { key: "service_name", description: "Single service name", sample: "Ceramic Coating", format: "plain" },
  short_url: { key: "short_url", description: "Short link to a quote / page", sample: "https://sdas.co/q1234", format: "url" },
  receipt_link: { key: "receipt_link", description: "Customer-facing receipt URL", sample: "https://sdas.co/r5678", format: "url" },
  booking_link: { key: "booking_link", description: "Booking page URL", sample: "https://sdas.co/book", format: "url" },
  authorize_url: { key: "authorize_url", description: "Add-on authorization URL (HMAC-token-bearing)", sample: "https://sdas.co/auth/abc", format: "url" },
  admin_url: { key: "admin_url", description: "Admin-side URL for staff", sample: "https://admin.sdas/q/123", format: "url" },
  portal_url: { key: "portal_url", description: "Customer portal URL", sample: "https://sdas.co/account", format: "url" },
  appointment_summary: { key: "appointment_summary", description: "Composite: appointment scheduled block (greeting + service + date/time + total)", sample: "Hi John, your appointment is scheduled:\nCeramic Coating\nMar 28 at 10:30 AM\nTotal: $299.00", format: "plain", composite: true },
  job_summary: { key: "job_summary", description: "Composite: services and optional vehicle, dash-joined", sample: "Ceramic Coating – 2024 Tesla Model 3", format: "plain", composite: true },
  transaction_greeting: { key: "transaction_greeting", description: "Composite: receipt prose for services-with-vehicle vs other", sample: "Your 2024 Tesla Model 3 is looking great.", format: "plain", composite: true },
  payment_info: { key: "payment_info", description: "Composite: deposit-aware payment status for customer prose", sample: "Deposit paid: $50.00. Balance due at service: $249.00.", format: "plain", composite: true },
  deposit_info: { key: "deposit_info", description: "Composite: short deposit status for staff prose", sample: "Deposit paid.", format: "plain", composite: true },
  hours_line: { key: "hours_line", description: "Composite: business hours prose (today-only OR full-week, varies by caller)", sample: "Open today until 6:00 PM", format: "plain", composite: true },
  summary_line: { key: "summary_line", description: "Composite: length-aware single-line receipt summary (160-char budget)", sample: "2024 Tesla Model 3 — $329.45", format: "plain", composite: true },
  first_name_greeting: { key: "first_name_greeting", description: "Composite: leading-comma name fragment (\", John\" or empty)", sample: ", John", format: "plain", composite: true },
  job_cancelled_line: { key: "job_cancelled_line", description: "Composite: cancellation note for void notifications (SMS shape)", sample: " Your scheduled service has been cancelled.", format: "plain", composite: true },
  reason_line: { key: "reason_line", description: "Composite: void reason note", sample: " Reason: Duplicate charge.", format: "plain", composite: true },
  message_to_customer: { key: "message_to_customer", description: "Operator-typed prose passed verbatim (addon-resend)", sample: "Hey, your add-on photo is here", format: "plain", composite: true },
  reason_label: { key: "reason_label", description: "Escalation reason (humanized)", sample: "Custom Quote Needed", format: "plain" },
  reason_code: { key: "reason_code", description: "Escalation reason code", sample: "custom_quote", format: "plain" },
  details: { key: "details", description: "Free-text details from agent", sample: "Customer wants ceramic coating for fleet of 5 vehicles", format: "plain" },
  cancellation_reason: { key: "cancellation_reason", description: "Reason for cancellation", sample: "Schedule conflict", format: "plain" },
  preferred_time: { key: "preferred_time", description: "Customer preferred callback time", sample: "Tomorrow afternoon", format: "plain" },
  customer_message_excerpt: { key: "customer_message_excerpt", description: "Excerpt of inbound customer message", sample: "Hi, I need a ceramic…", format: "plain" },
  transcript_summary: { key: "transcript_summary", description: "Voice call transcript summary", sample: "Customer asked about pricing for…", format: "plain" },
  inferred_customer_type: { key: "inferred_customer_type", description: "Inferred customer type (enthusiast / professional)", sample: "enthusiast", format: "plain" },
  expiration_minutes: { key: "expiration_minutes", description: "Add-on authorization expiration window", sample: "60", format: "plain" },
  pickup_delay_minutes: { key: "pickup_delay_minutes", description: "Add-on pickup-delay window", sample: "30", format: "plain" },
  issue_text: { key: "issue_text", description: "Add-on issue description (humanized)", sample: "Heavy interior staining", format: "plain" },
  issue_type: { key: "issue_type", description: "Add-on issue type code", sample: "staining", format: "plain" },
  issue_description: { key: "issue_description", description: "Free-text add-on issue description", sample: "Multiple coffee stains in driver seat", format: "plain" },
  friendly_name: { key: "friendly_name", description: "Humanized service name for add-on context", sample: "Stain Removal", format: "plain" },
  final_price: { key: "final_price", description: "Final add-on price", sample: "$65.00", format: "currency" },
  product_name: { key: "product_name", description: "Product display name", sample: "Carnauba Paste Wax", format: "plain" },
  product_slug: { key: "product_slug", description: "Product URL slug", sample: "carnauba-paste-wax", format: "plain" },
  category_name: { key: "category_name", description: "Category display name", sample: "Waxes & Sealants", format: "plain" },
  category_slug: { key: "category_slug", description: "Category URL slug", sample: "waxes-sealants", format: "plain" },
  service_filter: { key: "service_filter", description: "Pre-selected service filter for booking link", sample: "ceramic-coating", format: "plain" },
};

/** Total chip count exposed by the palette. */
export const SMS_PALETTE_KEYS: readonly string[] = Object.keys(SMS_PALETTE);
