-- Seed Data for Smart Detail Auto Spa & Supplies
-- This file runs after all migrations via `supabase db reset`

-- ============================================
-- Feature Flags (14 flags)
-- ============================================
INSERT INTO feature_flags (key, name, description, category, enabled) VALUES
  ('loyalty_rewards', 'Loyalty Rewards Program', 'Award points on purchases and allow redemption for discounts. Disabling hides loyalty from POS and portal, stops accumulation, and blocks redemption. Existing points are preserved.', 'Core POS', true),
  ('cancellation_fee', 'Cancellation Fees', 'Charge a fee when appointments are cancelled. Disabling removes the fee option from cancellation dialogs.', 'Core POS', true),
  ('sms_marketing', 'SMS Marketing Campaigns', 'Send SMS campaigns and lifecycle automations. Disabling stops all outbound marketing SMS. Transactional messages (reminders, confirmations) are not affected.', 'Marketing', true),
  ('email_marketing', 'Email Marketing Campaigns', 'Send email campaigns to customers. Disabling stops all outbound marketing emails. Transactional emails (confirmations, resets) are not affected.', 'Marketing', true),
  ('google_review_requests', 'Google Review Requests', 'Automatically request Google/Yelp reviews after service completion via lifecycle automations.', 'Marketing', true),
  ('two_way_sms', 'Two-Way SMS Messaging', 'Receive and respond to customer SMS messages. Includes team inbox, AI auto-responder, and auto-quotes. Disabling hides the messaging inbox and stops AI responses. STOP/START opt-out processing always remains active for compliance.', 'Communication', true),
  ('online_booking_payment', 'Online Booking Payment', 'Collect payment via Stripe during the online booking flow. Disabling allows booking without upfront payment.', 'Booking', true),
  ('waitlist', 'Waitlist', 'Allow customers to join a waitlist when slots are full. Sends notifications when spots open.', 'Booking', true),
  ('mobile_service', 'Mobile/On-Location Service', 'Offer on-location detailing with travel zones and fees. Disabling hides the mobile option from booking. Configure zones in Settings > Mobile Zones.', 'Booking', true),
  ('qbo_enabled', 'QuickBooks Online Integration', 'Sync transactions, customers, and catalog to QuickBooks Online for accounting. Configure connection in Settings > Integrations > QuickBooks.', 'Integrations', false),
  ('inventory_management', 'Inventory Management', 'Stock tracking, vendor management, and purchase orders. Hides inventory section from admin navigation when disabled.', 'Operations', true),
  ('recurring_services', 'Recurring Services', 'Subscription-based recurring service plans. Phase 10 — reserved for future use.', 'Future', false),
  ('photo_documentation', 'Photo Documentation', 'Before/after photo capture for service documentation. Phase 8 — reserved for future use.', 'Future', false),
  ('online_store', 'Online Store', 'Shopping cart, checkout, and order management. Phase 9 — reserved for future use.', 'Future', false);

-- ============================================
-- Mobile Zones (2 zones)
-- ============================================
INSERT INTO mobile_zones (name, min_distance_miles, max_distance_miles, surcharge, is_available, display_order) VALUES
  ('Zone 1 (0-5 miles)', 0, 5.0, 40.00, true, 1),
  ('Zone 2 (5-10 miles)', 5.0, 10.0, 80.00, true, 2);

-- ============================================
-- Product Categories (13 categories)
-- ============================================
INSERT INTO product_categories (name, slug, display_order) VALUES
  ('Accessories', 'accessories', 1),
  ('Paint Correction', 'paint-correction', 2),
  ('Brushes', 'brushes', 3),
  ('Microfibers', 'microfibers', 4),
  ('Paint Protection', 'paint-protection', 5),
  ('Cleaners', 'cleaners', 6),
  ('Tires & Trims', 'tires-trims', 7),
  ('Interior Care', 'interior-care', 8),
  ('Scents & Deodorizers', 'scents-deodorizers', 9),
  ('Soaps & Shampoos', 'soaps-shampoos', 10),
  ('Tools', 'tools', 11),
  ('Water', 'water', 12),
  ('Uncategorized', 'uncategorized', 13);

-- ============================================
-- Service Categories (7 categories)
-- ============================================
INSERT INTO service_categories (name, slug, display_order) VALUES
  ('Precision Express', 'precision-express', 1),
  ('Signature Detail', 'signature-detail', 2),
  ('Paint Correction & Restoration', 'paint-correction-restoration', 3),
  ('Ceramic Coatings', 'ceramic-coatings', 4),
  ('Exterior Enhancements', 'exterior-enhancements', 5),
  ('Interior Enhancements', 'interior-enhancements', 6),
  ('Specialty Vehicles', 'specialty-vehicles', 7);

-- ============================================
-- Default Role Permissions (~80 permissions)
-- ============================================

-- POS Operations
INSERT INTO permissions (permission_key, role, granted) VALUES
  -- open_close_register
  ('pos.open_close_register', 'super_admin', true),
  ('pos.open_close_register', 'admin', true),
  ('pos.open_close_register', 'cashier', true),
  ('pos.open_close_register', 'detailer', false),
  -- create_tickets
  ('pos.create_tickets', 'super_admin', true),
  ('pos.create_tickets', 'admin', true),
  ('pos.create_tickets', 'cashier', true),
  ('pos.create_tickets', 'detailer', false),
  -- add_items_to_ticket
  ('pos.add_items', 'super_admin', true),
  ('pos.add_items', 'admin', true),
  ('pos.add_items', 'cashier', true),
  ('pos.add_items', 'detailer', false),
  -- apply_coupons
  ('pos.apply_coupons', 'super_admin', true),
  ('pos.apply_coupons', 'admin', true),
  ('pos.apply_coupons', 'cashier', true),
  ('pos.apply_coupons', 'detailer', false),
  -- apply_loyalty
  ('pos.apply_loyalty', 'super_admin', true),
  ('pos.apply_loyalty', 'admin', true),
  ('pos.apply_loyalty', 'cashier', true),
  ('pos.apply_loyalty', 'detailer', false),
  -- process_card_payments
  ('pos.process_card', 'super_admin', true),
  ('pos.process_card', 'admin', true),
  ('pos.process_card', 'cashier', true),
  ('pos.process_card', 'detailer', false),
  -- process_cash_payments
  ('pos.process_cash', 'super_admin', true),
  ('pos.process_cash', 'admin', true),
  ('pos.process_cash', 'cashier', true),
  ('pos.process_cash', 'detailer', false),
  -- process_split_payments
  ('pos.process_split', 'super_admin', true),
  ('pos.process_split', 'admin', true),
  ('pos.process_split', 'cashier', true),
  ('pos.process_split', 'detailer', false),
  -- issue_refunds
  ('pos.issue_refunds', 'super_admin', true),
  ('pos.issue_refunds', 'admin', true),
  ('pos.issue_refunds', 'cashier', false),
  ('pos.issue_refunds', 'detailer', false),
  -- void_transactions
  ('pos.void_transactions', 'super_admin', true),
  ('pos.void_transactions', 'admin', false),
  ('pos.void_transactions', 'cashier', false),
  ('pos.void_transactions', 'detailer', false),
  -- manual_discounts
  ('pos.manual_discounts', 'super_admin', true),
  ('pos.manual_discounts', 'admin', true),
  ('pos.manual_discounts', 'cashier', false),
  ('pos.manual_discounts', 'detailer', false),
  -- override_pricing
  ('pos.override_pricing', 'super_admin', true),
  ('pos.override_pricing', 'admin', false),
  ('pos.override_pricing', 'cashier', false),
  ('pos.override_pricing', 'detailer', false),
  -- end_of_day
  ('pos.end_of_day', 'super_admin', true),
  ('pos.end_of_day', 'admin', true),
  ('pos.end_of_day', 'cashier', true),
  ('pos.end_of_day', 'detailer', false),

  -- Customer Management
  ('customers.view', 'super_admin', true),
  ('customers.view', 'admin', true),
  ('customers.view', 'cashier', true),
  ('customers.view', 'detailer', true),
  ('customers.create', 'super_admin', true),
  ('customers.create', 'admin', true),
  ('customers.create', 'cashier', true),
  ('customers.create', 'detailer', false),
  ('customers.edit', 'super_admin', true),
  ('customers.edit', 'admin', true),
  ('customers.edit', 'cashier', false),
  ('customers.edit', 'detailer', false),
  ('customers.delete', 'super_admin', true),
  ('customers.delete', 'admin', false),
  ('customers.delete', 'cashier', false),
  ('customers.delete', 'detailer', false),
  ('customers.view_history', 'super_admin', true),
  ('customers.view_history', 'admin', true),
  ('customers.view_history', 'cashier', true),
  ('customers.view_history', 'detailer', false),
  ('customers.view_loyalty', 'super_admin', true),
  ('customers.view_loyalty', 'admin', true),
  ('customers.view_loyalty', 'cashier', true),
  ('customers.view_loyalty', 'detailer', false),
  ('customers.adjust_loyalty', 'super_admin', true),
  ('customers.adjust_loyalty', 'admin', true),
  ('customers.adjust_loyalty', 'cashier', false),
  ('customers.adjust_loyalty', 'detailer', false),
  ('customers.export', 'super_admin', true),
  ('customers.export', 'admin', false),
  ('customers.export', 'cashier', false),
  ('customers.export', 'detailer', false),

  -- Appointments & Scheduling
  ('appointments.view_today', 'super_admin', true),
  ('appointments.view_today', 'admin', true),
  ('appointments.view_today', 'cashier', true),
  ('appointments.view_today', 'detailer', true),
  ('appointments.view_calendar', 'super_admin', true),
  ('appointments.view_calendar', 'admin', true),
  ('appointments.view_calendar', 'cashier', true),
  ('appointments.view_calendar', 'detailer', false),
  ('appointments.create', 'super_admin', true),
  ('appointments.create', 'admin', true),
  ('appointments.create', 'cashier', true),
  ('appointments.create', 'detailer', false),
  ('appointments.reschedule', 'super_admin', true),
  ('appointments.reschedule', 'admin', true),
  ('appointments.reschedule', 'cashier', true),
  ('appointments.reschedule', 'detailer', false),
  ('appointments.cancel', 'super_admin', true),
  ('appointments.cancel', 'admin', true),
  ('appointments.cancel', 'cashier', false),
  ('appointments.cancel', 'detailer', false),
  ('appointments.waive_fee', 'super_admin', true),
  ('appointments.waive_fee', 'admin', true),
  ('appointments.waive_fee', 'cashier', false),
  ('appointments.waive_fee', 'detailer', false),
  ('appointments.update_status', 'super_admin', true),
  ('appointments.update_status', 'admin', true),
  ('appointments.update_status', 'cashier', true),
  ('appointments.update_status', 'detailer', true),
  ('appointments.add_notes', 'super_admin', true),
  ('appointments.add_notes', 'admin', true),
  ('appointments.add_notes', 'cashier', true),
  ('appointments.add_notes', 'detailer', true),
  ('appointments.manage_schedule', 'super_admin', true),
  ('appointments.manage_schedule', 'admin', true),
  ('appointments.manage_schedule', 'cashier', false),
  ('appointments.manage_schedule', 'detailer', false),

  -- Products & Inventory
  ('products.view', 'super_admin', true),
  ('products.view', 'admin', true),
  ('products.view', 'cashier', true),
  ('products.view', 'detailer', true),
  ('products.edit', 'super_admin', true),
  ('products.edit', 'admin', true),
  ('products.edit', 'cashier', false),
  ('products.edit', 'detailer', false),
  ('products.delete', 'super_admin', true),
  ('products.delete', 'admin', false),
  ('products.delete', 'cashier', false),
  ('products.delete', 'detailer', false),
  ('inventory.view_stock', 'super_admin', true),
  ('inventory.view_stock', 'admin', true),
  ('inventory.view_stock', 'cashier', true),
  ('inventory.view_stock', 'detailer', false),
  ('inventory.adjust_stock', 'super_admin', true),
  ('inventory.adjust_stock', 'admin', true),
  ('inventory.adjust_stock', 'cashier', false),
  ('inventory.adjust_stock', 'detailer', false),
  ('inventory.manage_po', 'super_admin', true),
  ('inventory.manage_po', 'admin', true),
  ('inventory.manage_po', 'cashier', false),
  ('inventory.manage_po', 'detailer', false),
  ('inventory.receive', 'super_admin', true),
  ('inventory.receive', 'admin', true),
  ('inventory.receive', 'cashier', true),
  ('inventory.receive', 'detailer', false),
  ('inventory.view_costs', 'super_admin', true),
  ('inventory.view_costs', 'admin', true),
  ('inventory.view_costs', 'cashier', false),
  ('inventory.view_costs', 'detailer', false),
  ('inventory.manage_vendors', 'super_admin', true),
  ('inventory.manage_vendors', 'admin', true),
  ('inventory.manage_vendors', 'cashier', false),
  ('inventory.manage_vendors', 'detailer', false),

  -- Services
  ('services.view', 'super_admin', true),
  ('services.view', 'admin', true),
  ('services.view', 'cashier', true),
  ('services.view', 'detailer', true),
  ('services.edit', 'super_admin', true),
  ('services.edit', 'admin', true),
  ('services.edit', 'cashier', false),
  ('services.edit', 'detailer', false),
  ('services.delete', 'super_admin', true),
  ('services.delete', 'admin', false),
  ('services.delete', 'cashier', false),
  ('services.delete', 'detailer', false),
  ('services.manage_addons', 'super_admin', true),
  ('services.manage_addons', 'admin', true),
  ('services.manage_addons', 'cashier', false),
  ('services.manage_addons', 'detailer', false),
  ('services.set_pricing', 'super_admin', true),
  ('services.set_pricing', 'admin', true),
  ('services.set_pricing', 'cashier', false),
  ('services.set_pricing', 'detailer', false),

  -- Marketing & Campaigns
  ('marketing.campaigns', 'super_admin', true),
  ('marketing.campaigns', 'admin', true),
  ('marketing.campaigns', 'cashier', false),
  ('marketing.campaigns', 'detailer', false),
  ('marketing.coupons', 'super_admin', true),
  ('marketing.coupons', 'admin', true),
  ('marketing.coupons', 'cashier', false),
  ('marketing.coupons', 'detailer', false),
  ('marketing.analytics', 'super_admin', true),
  ('marketing.analytics', 'admin', true),
  ('marketing.analytics', 'cashier', false),
  ('marketing.analytics', 'detailer', false),
  ('marketing.lifecycle_rules', 'super_admin', true),
  ('marketing.lifecycle_rules', 'admin', true),
  ('marketing.lifecycle_rules', 'cashier', false),
  ('marketing.lifecycle_rules', 'detailer', false),
  ('marketing.two_way_sms', 'super_admin', true),
  ('marketing.two_way_sms', 'admin', true),
  ('marketing.two_way_sms', 'cashier', false),
  ('marketing.two_way_sms', 'detailer', false),

  -- Quotes
  ('quotes.create', 'super_admin', true),
  ('quotes.create', 'admin', true),
  ('quotes.create', 'cashier', true),
  ('quotes.create', 'detailer', false),
  ('quotes.send', 'super_admin', true),
  ('quotes.send', 'admin', true),
  ('quotes.send', 'cashier', true),
  ('quotes.send', 'detailer', false),
  ('quotes.convert', 'super_admin', true),
  ('quotes.convert', 'admin', true),
  ('quotes.convert', 'cashier', true),
  ('quotes.convert', 'detailer', false),

  -- Photos
  ('photos.upload', 'super_admin', true),
  ('photos.upload', 'admin', true),
  ('photos.upload', 'cashier', true),
  ('photos.upload', 'detailer', true),
  ('photos.view', 'super_admin', true),
  ('photos.view', 'admin', true),
  ('photos.view', 'cashier', true),
  ('photos.view', 'detailer', true),
  ('photos.delete', 'super_admin', true),
  ('photos.delete', 'admin', true),
  ('photos.delete', 'cashier', false),
  ('photos.delete', 'detailer', false),
  ('photos.approve_marketing', 'super_admin', true),
  ('photos.approve_marketing', 'admin', true),
  ('photos.approve_marketing', 'cashier', false),
  ('photos.approve_marketing', 'detailer', false),

  -- Financial & Reporting
  ('reports.revenue', 'super_admin', true),
  ('reports.revenue', 'admin', true),
  ('reports.revenue', 'cashier', false),
  ('reports.revenue', 'detailer', false),
  ('reports.financial_detail', 'super_admin', true),
  ('reports.financial_detail', 'admin', false),
  ('reports.financial_detail', 'cashier', false),
  ('reports.financial_detail', 'detailer', false),
  ('reports.cost_margin', 'super_admin', true),
  ('reports.cost_margin', 'admin', false),
  ('reports.cost_margin', 'cashier', false),
  ('reports.cost_margin', 'detailer', false),
  ('reports.employee_tips', 'super_admin', true),
  ('reports.employee_tips', 'admin', false),
  ('reports.employee_tips', 'cashier', false),
  ('reports.employee_tips', 'detailer', false),
  ('reports.own_tips', 'super_admin', true),
  ('reports.own_tips', 'admin', true),
  ('reports.own_tips', 'cashier', true),
  ('reports.own_tips', 'detailer', true),
  ('reports.export', 'super_admin', true),
  ('reports.export', 'admin', false),
  ('reports.export', 'cashier', false),
  ('reports.export', 'detailer', false),
  ('reports.quickbooks_status', 'super_admin', true),
  ('reports.quickbooks_status', 'admin', false),
  ('reports.quickbooks_status', 'cashier', false),
  ('reports.quickbooks_status', 'detailer', false),

  -- Employee Management
  ('staff.clock_self', 'super_admin', true),
  ('staff.clock_self', 'admin', true),
  ('staff.clock_self', 'cashier', true),
  ('staff.clock_self', 'detailer', true),
  ('staff.view_own_hours', 'super_admin', true),
  ('staff.view_own_hours', 'admin', true),
  ('staff.view_own_hours', 'cashier', true),
  ('staff.view_own_hours', 'detailer', true),
  ('staff.view_all_hours', 'super_admin', true),
  ('staff.view_all_hours', 'admin', true),
  ('staff.view_all_hours', 'cashier', false),
  ('staff.view_all_hours', 'detailer', false),
  ('staff.edit_time', 'super_admin', true),
  ('staff.edit_time', 'admin', false),
  ('staff.edit_time', 'cashier', false),
  ('staff.edit_time', 'detailer', false),

  -- System & Settings
  ('settings.feature_toggles', 'super_admin', true),
  ('settings.feature_toggles', 'admin', false),
  ('settings.feature_toggles', 'cashier', false),
  ('settings.feature_toggles', 'detailer', false),
  ('settings.tax_payment', 'super_admin', true),
  ('settings.tax_payment', 'admin', false),
  ('settings.tax_payment', 'cashier', false),
  ('settings.tax_payment', 'detailer', false),
  ('settings.manage_users', 'super_admin', true),
  ('settings.manage_users', 'admin', false),
  ('settings.manage_users', 'cashier', false),
  ('settings.manage_users', 'detailer', false),
  ('settings.roles_permissions', 'super_admin', true),
  ('settings.roles_permissions', 'admin', false),
  ('settings.roles_permissions', 'cashier', false),
  ('settings.roles_permissions', 'detailer', false),
  ('settings.business_hours', 'super_admin', true),
  ('settings.business_hours', 'admin', true),
  ('settings.business_hours', 'cashier', false),
  ('settings.business_hours', 'detailer', false),
  ('settings.audit_log', 'super_admin', true),
  ('settings.audit_log', 'admin', false),
  ('settings.audit_log', 'cashier', false),
  ('settings.audit_log', 'detailer', false),
  ('settings.api_keys', 'super_admin', true),
  ('settings.api_keys', 'admin', false),
  ('settings.api_keys', 'cashier', false),
  ('settings.api_keys', 'detailer', false),
  ('settings.backup_export', 'super_admin', true),
  ('settings.backup_export', 'admin', false),
  ('settings.backup_export', 'cashier', false),
  ('settings.backup_export', 'detailer', false);

-- ============================================
-- Business Settings
-- ============================================
INSERT INTO business_settings (key, value, description) VALUES
  ('business_name', '"Smart Detail Auto Spa & Supplies"', 'Business display name'),
  ('business_address', '{"line1": "2021 Lomita Blvd", "city": "Lomita", "state": "CA", "zip": "90717"}', 'Business address'),
  ('business_phone', '"+13109990000"', 'Business phone number'),
  ('business_hours', '{"tuesday": {"open": "09:00", "close": "17:00"}, "wednesday": {"open": "09:00", "close": "17:00"}, "thursday": {"open": "09:00", "close": "17:00"}, "friday": {"open": "09:00", "close": "17:00"}, "saturday": {"open": "09:00", "close": "17:00"}}', 'Store operating hours'),
  ('tax_rate', '0.1025', 'CA sales tax rate (10.25%)'),
  ('tax_products_only', 'true', 'Only charge tax on products, not services'),
  ('tip_presets', '[15, 20, 25]', 'Tip percentage presets for POS'),
  ('cc_fee_rate', '0.05', 'Credit card fee rate deducted from tips (5%)'),
  ('loyalty_earn_rate', '1', 'Points earned per $1 spent'),
  ('loyalty_redeem_rate', '0.05', 'Dollar value per point ($5 per 100 points = $0.05/point)'),
  ('loyalty_redeem_minimum', '100', 'Minimum points to redeem'),
  ('appointment_buffer_minutes', '30', 'Buffer time between appointments'),
  ('mobile_travel_buffer_minutes', '30', 'Travel buffer for mobile appointments'),
  ('cancellation_window_hours', '24', 'Free cancellation window in hours'),
  ('receipt_email_enabled', 'true', 'Send receipts via email'),
  ('receipt_sms_enabled', 'true', 'Send receipts via SMS'),
  ('water_sku', '"0000001"', 'SKU for water product (excluded from loyalty)');
