import { cache } from 'react';
import { createClient as createServerClient } from '@/lib/supabase/server';
import { createAnonClient } from '@/lib/supabase/anon';
import type { Metadata } from 'next';
import type { PageSeo } from '@/lib/supabase/types';

// ---------------------------------------------------------------------------
// Per-Page SEO Data Layer
// ---------------------------------------------------------------------------

async function getSupabase() {
  try {
    return await createServerClient();
  } catch {
    return createAnonClient();
  }
}

/**
 * Get SEO overrides for a specific page path.
 * Returns null if no custom SEO exists for this page.
 */
export const getPageSeo = cache(async (pagePath: string): Promise<PageSeo | null> => {
  const supabase = await getSupabase();
  const { data } = await supabase
    .from('page_seo')
    .select('*')
    .eq('page_path', pagePath)
    .maybeSingle();
  return data as PageSeo | null;
});

/**
 * Merge auto-generated metadata with admin SEO overrides.
 * Admin overrides take priority when present, auto-generated values are fallbacks.
 */
export function mergeMetadata(
  autoGenerated: Metadata,
  overrides: PageSeo | null
): Metadata {
  if (!overrides) return autoGenerated;

  const merged: Metadata = { ...autoGenerated };

  // Title
  if (overrides.seo_title) {
    merged.title = overrides.seo_title;
  }

  // Description
  if (overrides.meta_description) {
    merged.description = overrides.meta_description;
  }

  // Keywords
  if (overrides.meta_keywords) {
    merged.keywords = overrides.meta_keywords.split(',').map((k) => k.trim());
  }

  // Canonical URL
  if (overrides.canonical_url) {
    merged.alternates = {
      ...merged.alternates,
      canonical: overrides.canonical_url,
    };
  }

  // Robots
  if (overrides.robots_directive && overrides.robots_directive !== 'index,follow') {
    merged.robots = overrides.robots_directive;
  }

  // OpenGraph
  const ogTitle = overrides.og_title || overrides.seo_title;
  const ogDescription = overrides.og_description || overrides.meta_description;
  if (ogTitle || ogDescription || overrides.og_image_url) {
    merged.openGraph = {
      ...(merged.openGraph as Record<string, unknown>),
      ...(ogTitle ? { title: ogTitle } : {}),
      ...(ogDescription ? { description: ogDescription } : {}),
      ...(overrides.og_image_url ? { images: [overrides.og_image_url] } : {}),
    };
  }

  // Twitter
  if (ogTitle || ogDescription) {
    merged.twitter = {
      ...(merged.twitter as Record<string, unknown>),
      ...(ogTitle ? { title: ogTitle } : {}),
      ...(ogDescription ? { description: ogDescription } : {}),
    };
  }

  return merged;
}
