import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { purchaseOrderCreateSchema } from '@/lib/utils/validation';

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = createAdminClient();

    const { data: employee } = await admin
      .from('employees')
      .select('role')
      .eq('auth_user_id', user.id)
      .single();
    if (!employee || !['super_admin', 'admin'].includes(employee.role)) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const vendorId = searchParams.get('vendor_id');

    let query = admin
      .from('purchase_orders')
      .select(`
        *,
        vendors(id, name),
        employees!purchase_orders_created_by_fkey(id, first_name, last_name),
        purchase_order_items(id, product_id, quantity_ordered, quantity_received, unit_cost, products(id, name, sku))
      `)
      .order('created_at', { ascending: false });

    if (status) {
      query = query.eq('status', status);
    }
    if (vendorId) {
      query = query.eq('vendor_id', vendorId);
    }

    const { data, error } = await query;
    if (error) {
      console.error('List purchase orders error:', error);
      return NextResponse.json({ error: 'Failed to load purchase orders' }, { status: 500 });
    }

    // Reshape joined employee
    const orders = (data ?? []).map((po: Record<string, unknown>) => ({
      ...po,
      vendor: po.vendors,
      created_by_employee: po.employees,
      items: po.purchase_order_items,
      vendors: undefined,
      employees: undefined,
      purchase_order_items: undefined,
    }));

    return NextResponse.json({ data: orders });
  } catch (err) {
    console.error('GET purchase-orders error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = createAdminClient();

    const { data: employee } = await admin
      .from('employees')
      .select('id, role')
      .eq('auth_user_id', user.id)
      .single();
    if (!employee || !['super_admin', 'admin'].includes(employee.role)) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await request.json();
    const parsed = purchaseOrderCreateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 });
    }

    const { vendor_id, notes, items } = parsed.data;

    // Create purchase order (po_number auto-generated by trigger)
    const { data: po, error: poError } = await admin
      .from('purchase_orders')
      .insert({
        vendor_id,
        notes: notes || null,
        status: 'draft',
        created_by: employee.id,
      })
      .select('*')
      .single();

    if (poError || !po) {
      console.error('Create PO error:', poError);
      return NextResponse.json({ error: 'Failed to create purchase order' }, { status: 500 });
    }

    // Insert items
    const itemRows = items.map((item) => ({
      purchase_order_id: po.id,
      product_id: item.product_id,
      quantity_ordered: item.quantity_ordered,
      unit_cost: item.unit_cost,
    }));

    const { error: itemsError } = await admin
      .from('purchase_order_items')
      .insert(itemRows);

    if (itemsError) {
      console.error('Create PO items error:', itemsError);
      // Clean up the PO
      await admin.from('purchase_orders').delete().eq('id', po.id);
      return NextResponse.json({ error: 'Failed to create purchase order items' }, { status: 500 });
    }

    return NextResponse.json({ data: po }, { status: 201 });
  } catch (err) {
    console.error('POST purchase-orders error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
